# This is a basic workflow to help you get started with Actions

name: artifact CI
# Controls when the action will run. 
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create file to upload
        run: echo "Testando a gestão de artefatos entre os stages" > test.txt
      - name: Cat the value inside new file
        run: cat test.txt
      - name: Upload artifact to another job
        uses: actions/upload-artifact@v2
        with:
          name: output-test
          path: test.txt
  download-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-test
      - name: Cat artifact
        run: cat test.txt
