# This is a basic workflow to help you get started with Actions

name: CI lower string
# Controls when the action will run. 
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  down-letters:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env:
    #   IMAGE_NAME: echo "alertEmailDigest" | tr '[:upper:]' '[:lower:]'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set data
        run: echo '::set-output name=imageName::"alertEmailDigest" | tr '[:upper:]' '[:lower:]''
      - name: Print
        run: echo "${{ steps.random-color-generator.outputs.imageName }}"